import Env from '@ioc:Adonis/Core/Env'

export default Env.rules({
  PORT: Env.schema.number(),
  HOST: Env.schema.string({ format: 'host' }),
  NODE_ENV: Env.schema.enum.optional(['development', 'production', 'test'] as const),
  APP_KEY: Env.schema.string(),
  DRIVE_DISK: Env.schema.enum(['local', 's3'] as const),
  APP_NAME: Env.schema.string(),
  DB_CONNECTION: Env.schema.string(),
  MYSQL_HOST: Env.schema.string({ format: 'host' }),
  MYSQL_PORT: Env.schema.number(),
  MYSQL_USER: Env.schema.string(),
  MYSQL_PASSWORD: Env.schema.string.optional(),
  MYSQL_DB_NAME: Env.schema.string(),
  BULL_REDIS_HOST: Env.schema.string({ format: 'host' }),
  BULL_REDIS_PORT: Env.schema.number(),
  BULL_REDIS_PASSWORD: Env.schema.string.optional(),
  S3_KEY: Env.schema.string(),
  S3_SECRET: Env.schema.string(),
  S3_BUCKET: Env.schema.string(),
  S3_REGION: Env.schema.string(),
  S3_ENDPOINT: Env.schema.string(),
  S3_DOMAIN: Env.schema.string(),
  SENDGRID_API: Env.schema.string(),
  // STRIPE_SECRET_KEY: Env.schema.string(),
  // STRIPE_PUBLIC_KEY: Env.schema.string(),
  // OPENAI_KEY: Env.schema.string(),
  // REDIS_CONNECTION: Env.schema.enum(['local', 'cache'] as const),
  // REDIS_HOST: Env.schema.string({ format: 'host' }),
  // REDIS_PORT: Env.schema.number(),
  // REDIS_PASSWORD: Env.schema.string.optional(),
})
